### ISSUE TITLE
lib/index.d.ts contains references to un-bundled files

### ISSUE THREAD

**Issue by EricCrosson** [mostjs-community/most-rx-utils#3]
Hey there, sweet package! Really looking forward to using this in typescript. Right now the types appear to be broken, I popped open the hood and saw this

```
/** @license MIT License (c) copyright 2019 original author or authors */
/** @author Carlos Zimmerle */
import { Stream } from '@most/types';
declare const interval: (period: number) => Stream<number>;
declare const timer: import("../../../../../../Users/Carlos/Documents/GitHub/most-rx-utils/node_modules/@most/prelude").CurriedFunction2<number | Date, number | null | undefined, Stream<number>>;
declare const bufferCount: import("../../../../../../Users/Carlos/Documents/GitHub/most-rx-utils/node_modules/@most/prelude").CurriedFunction3<number, number | null | undefined, Stream<any>, Stream<any[]>>;
declare const bufferToggle: import("../../../../../../Users/Carlos/Documents/GitHub/most-rx-utils/node_modules/@most/prelude").CurriedFunction3<Stream<any>, Stream<any>, Stream<any>, Stream<any[]>>;
declare const bufferTime: import("../../../../../../Users/Carlos/Documents/GitHub/most-rx-utils/node_modules/@most/prelude").CurriedFunction3<number, number | null | undefined, Stream<any>, Stream<any[]>>;
export { interval, timer, bufferCount, bufferToggle, bufferTime };
```

Not sure how that monster relative path got in there but it's not portable in its current form

**Comment by carloszimm** [comment]
Hey, @EricCrosson !

I'm glad you liked it, and sorry for taking long. It's been a rough/busy time.
Well, it appears that some generated code ended up being uploaded to NPM.
Overall, it doesn't seem to be a critical issue.
I'll be looking into it till the weekend and keep you updated.
Thank you!

**Comment by EricCrosson** [comment]
No sweat @carloszimm, as you said it's just the type hints that are affected. Cheers!

**Comment by carloszimm** [comment]
Hey, @EricCrosson! I just bumped a new version (1.1.3), could you check if it has solved the problem for you?

Apparently, the problem was related to an old version of typescript

**Comment by EricCrosson** [comment]
Looks great to me! Nice work @carloszimm
